#!/usr/bin/ruby

# Copyright (C) 2013  Olathe on GitHub
# 
# This file is part of redcarpet.
# 
# Redcarpet is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Redcarpet is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with redcarpet.  If not, see <http://www.gnu.org/licenses/>.

TIME_BETWEEN_TOS_ACCEPTANCES_IN_SECONDS = 900
TIME_BETWEEN_SSID_CHECKS_IN_SECONDS     = 10

SSID             = 'RedCarpetInn'
ACCEPT_TERMS_URL = 'http://192.168.17.1:3456/Login?ticket=Free'

require 'open3'
require 'open-uri'

def get_ssid
  begin
    # Handle Linux
    result = Open3.capture2e('iwconfig').first.scan(/ESSID:"(.+?)"/)
  rescue Errno::ENOENT
    begin
      # Handle Windows
      result = Open3.capture2e('netsh wlan show interfaces').first.scan(/ SSID\s+: (.+?)\n/)
    rescue
      # Handle failure
      result = []
    end
  end
  result.empty? ? nil : result.first.first
end

next_ssid_check     = Time.now.to_i
next_tos_acceptance = 1.0/0.0
was_disconnected = true
loop do
  begin
    if Time.now.to_i >= next_ssid_check
      if get_ssid == SSID
        next_tos_acceptance = Time.now.to_i if was_disconnected
        was_disconnected = false
      else
        puts "[#{ Time.now }] Not connected to #{ SSID }"
        next_tos_acceptance = 1.0/0.0
        was_disconnected = true
      end
      next_ssid_check = Time.now.to_i + TIME_BETWEEN_SSID_CHECKS_IN_SECONDS
    end
    
    if Time.now.to_i >= next_tos_acceptance
      print "[#{ Time.now }] Accepting terms of service..."
      open(ACCEPT_TERMS_URL) do |f|
        puts((f.status.first == '200') ? "success" : "FAIL!")
      end
      next_tos_acceptance = Time.now.to_i + TIME_BETWEEN_TOS_ACCEPTANCES_IN_SECONDS
    end
  rescue Exception => e
    $stderr.puts e.inspect
  end
  sleep 1
end
